### ISSUE TITLE
Create package specific object

### ISSUE THREAD

**Issue by Wolfffff** [Wolfffff/RATrak#9]
Create package specific object, tentatively called trak, that combines the speed information and metadata into a singular object.

Along with this, we should have a custom summary function for class 'trak' that returns an amalgamated form of the two

**Comment by simfor** [comment]
The idea here is to have an internally consistent data structure that we pass to all/most of our functions. One rough suggestion:
- readBinary returns an object like list(speed, metadata). Lets call it trak
- flies.avgByGroup returns another updated object. Lets call it trak.avg

**Comment by simfor** [comment]
Priority order:
1. Make the object and make all the relevant functions take this object as input
2. Maybe make a summary function etc. TBD

**Comment by Wolfffff** [comment]
4dae786

**Comment by Wolfffff** [comment]
@simfor Check out the last commit when you have a chance

d455c48
